version: '3.8'
services:
  postgres-dev-server:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookmarks

  postgres-test-server:
    image: postgres:16.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - bookmarks

volumes:
  postgres-data:

networks:
  bookmarks:
